#!/bin/sh
set -e

if [ -e /etc/etckeeper/etckeeper.conf ]; then
	. /etc/etckeeper/etckeeper.conf
fi

if [ ! -z "$GIT_COMMIT_OPTIONS" ]; then
	export GIT_COMMIT_OPTIONS
fi
if [ ! -z "$HIGHLEVEL_PACKAGE_MANAGER" ]; then
	export HIGHLEVEL_PACKAGE_MANAGER
fi
if [ ! -z "$LOWLEVEL_PACKAGE_MANAGER" ]; then
	export LOWLEVEL_PACKAGE_MANAGER
fi

if [ -z "$1" ]; then
	echo "usage: etckeeper command [directory]" >&2
	exit 1
fi
command="$1"
shift 1

if [ ! -d "/etc/etckeeper/$command.d" ]; then
	echo "etckeeper: /etc/etckeeper/$command.d does not exist" >&2
	exit 1
fi

if [ -n "$1" ]; then
	cd "$1"
else
	cd /etc
fi

run-parts --exit-on-error "/etc/etckeeper/$command.d"
