#!/bin/sh
set -e

if [ -z "$1" ]; then
	echo "usage: etckeeper command [directory]" >&2
	exit 1
fi
command="$1"
shift 1

if [ ! -d "/etc/etckeeper/$command.d" ]; then
	echo "etckeeper: /etc/etckeeper/$command.d does not exist" >&2
	exit 1
fi

if [ -n "$1" ]; then
	cd "$1"
else
	cd /etc
fi

run-parts "/etc/etckeeper/$command.d"
