#!/bin/sh
set -e
if [ -x .git/hooks/pre-commit ]; then
	if ! grep -q etc-pre-commit .git/hooks/pre-commit; then
		echo "warning: .git/hooks/pre-commit needs to be manually modifed to run etc-pre-commit" >&2
	fi
else
	echo <<EOF >>.git/hooks/pre-commit
#!/bin/sh
# pre-commit hook for etckeeper. Calls etc-pre-commit to store metadata
# and do sanity checks.
set -e
etc-pre-commit
EOF
	chmod +x .git/hooks/pre-commit
fi
