#!/bin/sh
set -e

message="$1"
hostname=`hostname -f 2>/dev/null || hostname`

if [ "$VCS" = git ] && [ -d .git ]; then
	if [ -n "$SUDO_USER" ]; then
		export GIT_COMMITTER_NAME="$SUDO_USER"
		export GIT_COMMITTER_EMAIL="$SUDO_USER@$hostname"
	fi
	if [ -n "$message" ]; then
		git commit $GIT_COMMIT_OPTIONS -m "$message"
	else
		git commit $GIT_COMMIT_OPTIONS
	fi
elif [ "$VCS" = hg ] && [ -d .hg ]; then
	if [ -n "$SUDO_USER" ]; then
		export LOGNAME="$SUDO_USER"
	fi
	if [ -n "$message" ]; then
		hg commit $HG_COMMIT_OPTIONS -m "$message"
	else
		hg commit $HG_COMMIT_OPTIONS
	fi
elif [ "$VCS" = bzr ] && [ -d .bzr ]; then
	if [ -n "$SUDO_USER" ]; then
		export EMAIL="$SUDO_USER <$SUDO_USER@$hostname>"
	fi
	if [ -n "$message" ]; then
		bzr commit $BZR_COMMIT_OPTIONS -m "$message"
	else
		bzr commit $BZR_COMMIT_OPTIONS
	fi
elif [ "$VCS" = darcs ] && [ -d _darcs ]; then
	logfile="$( mktemp -t etckeeper-$VCS.XXXXXXXXXX )"
	printf "%b" "$message" > "$logfile"
	darcs record $DARCS_COMMIT_OPTIONS --logfile="$logfile"
	rm -f "$logfile"
	unset logfile
fi
