#!/bin/sh
set -e

message="$1"
hostname=`hostname -f 2>/dev/null || hostname`

USER=
if [ -n "$SUDO_USER" ]; then
	USER="$SUDO_USER"
else
	# try to check tty ownership, in case user su'd to root
	TTY="$(tty 2>/dev/null || true)"
	if [ -n "$TTY" ] && [ -c "$TTY" ]; then
		USER="$(find "$TTY" -printf "%u")"
	fi
fi

if [ "$VCS" = git ] && [ -d .git ]; then
	if [ -n "$USER" ]; then
		export GIT_COMMITTER_NAME="$USER"
		export GIT_COMMITTER_EMAIL="$USER@$hostname"
	fi
	if [ -n "$message" ]; then
		git commit $GIT_COMMIT_OPTIONS -m "$message"
	else
		git commit $GIT_COMMIT_OPTIONS
	fi
elif [ "$VCS" = hg ] && [ -d .hg ]; then
	if [ -n "$USER" ]; then
		export LOGNAME="$USER"
	fi
	if [ -n "$message" ]; then
		hg commit $HG_COMMIT_OPTIONS -m "$message"
	else
		hg commit $HG_COMMIT_OPTIONS
	fi
elif [ "$VCS" = bzr ] && [ -d .bzr ]; then
	if [ -n "$USER" ]; then
		export EMAIL="$USER <$USER@$hostname>"
		BZR_AUTHOR='--author="root <root@$hostname>"'
	fi
	if [ -n "$message" ]; then
		bzr commit "$BZR_AUTHOR" $BZR_COMMIT_OPTIONS -m "$message"
	else
		bzr commit "$BZR_AUTHOR" $BZR_COMMIT_OPTIONS
	fi
elif [ "$VCS" = darcs ] && [ -d _darcs ]; then
	logfile="$( mktemp -t etckeeper-$VCS.XXXXXXXXXX )"
	printf "%b" "$message" > "$logfile"
	darcs record $DARCS_COMMIT_OPTIONS --logfile="$logfile"
	rm -f "$logfile"
	unset logfile
fi
