#!/bin/sh
set -e

if [ "$VCS" = git ] || [ "$VCS" = hg ] || [ "$VCS" = bzr ]; then
	special=$(find -not -type d -not -type f -not -type l | grep -v /.git/ | grep -v /.hg/ | grep -v /.bzr/) || true
	if [ -n "$special" ]; then
		echo "etckeeper warning: special files could cause problems with $VCS:" >&2
		echo "$special" >&2
	fi
fi

true
