#!/bin/sh
set -e

# Remove the .metadata file if we're using .fix-metadata
if [ -f .metadata ] && [ -f .fix-metadata ]; then
	# Don't want to do anything permanent if user is mistakenly
	# running etckeeper without first setting VCS.
	if [ "x$VCS" != "x" ]; then
		$VCS rm .metadata
	fi
fi
