#!/bin/sh
set -e

# Tell the user if the .metadata binary file is still lying around.
if [ -f .metadata ] && [ -f .fix-metadata ]; then
	echo "etckeeper warning: The .metadata file is obsolete.  You should delete it." >&2
fi
