#!/bin/sh

# TODO
# Not sure if it is the case with Mercurial ?
set -e
hardlinks=$(find -type f -not -links 1 | grep -v /.hg/) || true
if [ -n "$hardlinks" ]; then
	echo "etckeeper warning: hardlinked files could cause problems with mercurial:" >&2
	echo "$hardlinks" >&2
fi
