#!/bin/sh
set -e

if [ -d .hg ]; then

	# TODO: figure out what packages were acted on by the apt run, and
	# include that info in the commit message
	message="committing changes after apt run"

	# ignore exit code since it exits nonzero if there is nothing to do
	hg commit $GIT_COMMIT_OPTIONS -m "$message" || true
fi
