#!/bin/sh
set -e

echo "** Warning: This will DESTROY all recorded history for $ETCKEEPER_DIR,"
echo "** including the $VCS repository and ignore file."
echo ""
printf "Are you sure you want to do this? [yN] "
read answer
case "$answer" in 
	Y|y|yes|YES)
		echo "Proceeding.."
		exit 0
	;;
	*)
		echo "Aborting etckeeper uninit."
		exit 1
	;;
esac
