#!/bin/sh
set -e

if [ "$VCS" = git ]; then
	[ -d .git ] && ! LANG=C git-status 2>&1 | grep -q "working directory clean"
elif [ "$VCS" = hg ]; then
	[ -d .hg ] && ! hg status 2>&1 | wc -l | grep -q "^0$"
fi
