#!/bin/sh
set -e
if [ ! -e .gitignore ]; then
	cat >.gitignore <<EOF
*~

# new and old versions of conffiles, stored by dpkg
*.dpkg-*

# mount(8) records system state here, no need to keep these in git
blkid.tab(|.old)
mtab
EOF
fi
