#!/bin/sh
set -e
if [ -x .git/hooks/pre-commit ]; then
	if ! grep -q "etckeeper pre-commit" .git/hooks/pre-commit; then
		echo "etckeeper warning: .git/hooks/pre-commit needs to be manually modifed to run: etckeeper pre-commit `pwd`" >&2
	fi
else
	cat >.git/hooks/pre-commit <<EOF
#!/bin/sh
# pre-commit hook for etckeeper, to store metadata and do sanity checks
set -e
etckeeper pre-commit `pwd`
EOF
	chmod +x .git/hooks/pre-commit
fi
