#!/bin/sh
set -e
if [ ! -e .gitignore ]; then
	if [ "$LOWLEVEL_PACKAGE_MANAGER" = dpkg ]; then
		cat >.gitignore <<EOF
# new and old versions of conffiles, stored by dpkg
*.dpkg-*
EOF
	fi
	cat >>.gitignore <<EOF
*~

# mount(8) records system state here, no need to keep these in git
blkid.tab
blkid.tab.old

# some other files in /etc that typically do not need to be tracked
ld.so.cache
mtab
.pwd.lock
network/run
adjtime

EOF
fi
