#!/bin/sh
set -e
if [ -e .hg/hgrc ] && grep "^\[hooks\]" .hg/hgrc; then
	echo "etckeeper warning: [hooks] section in .hg/hgrc  needs to be manually modified to run: etckeeper pre-commit `pwd`" >&2
else
	touch
	cat >>.hg/hgrc <<EOF
[hooks]
# pre-commit hook for etckeeper, to store metadata and do sanity checks
precommit = etckeeper pre-commit `pwd`
EOF
fi
